// File generated by flutterfire configure for project splitmate-efcdb
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGx1EnrgdPZmdOSFFKsJXYRU8c6UnEcgw',
    appId: '1:309873103927:web:df3881faaca53317801bb2',
    messagingSenderId: '309873103927',
    projectId: 'splitmate-efcdb',
    authDomain: 'splitmate-efcdb.firebaseapp.com',
    storageBucket: 'splitmate-efcdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimZh7dC2IBw2hJV2ewF0MHJ5eTpwLW0Q',
    appId: '1:309873103927:android:e1a0bfe5ff253d9b801bb2',
    messagingSenderId: '309873103927',
    projectId: 'splitmate-efcdb',
    storageBucket: 'splitmate-efcdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcZdxNJttClTIp9znihX0TVIzxeGwr-sM',
    appId: '1:309873103927:ios:b6f72ee9540280fd801bb2',
    messagingSenderId: '309873103927',
    projectId: 'splitmate-efcdb',
    storageBucket: 'splitmate-efcdb.firebasestorage.app',
    iosBundleId: 'com.splitmate.splitmate',
  );
}